export const gameList = [
  {
    id: 1,
    name: "Dawnshard",
    type: "TCG",
    desc: "Free-to-play multiplayer card game with unique, AI-generated decks.",
    img: "/dawnlogo.png",
    overview: "Dawnshard is a free-to-play multiplayer card game for PC and mobile, where players compete using unique, AI-generated decks. Set across 6 fantasy worlds, the game's innovative algorithm ensures that every Card Set is unique. Players can buy, sell, and trade their cards across partner NFT marketplaces, creating a dynamic, permissionless trading experience. Earn Battle Pass points by completing matches and unlock rewards like Tethras and Debristar to enhance your decks.",
    category: "Card Game",
    images: ["/Minibase Photos/Dawnshard/Dawnshard Gaming Nights.png", "/Minibase Photos/Dawnshard/Frame.png", "/Minibase Photos/Dawnshard/GTF4E3FWkAAdOXw.jpeg"],
    faqData: [
      { question: "How are cards generated?", answer: "Each deck is AI-generated, ensuring that no two decks are the same." },
      { question: "Can I trade my cards?", answer: "Yes, all cards can be traded on partner NFT marketplaces." },
      { question: "What rewards can I earn?", answer: "Players earn Battle Pass points, unique cards, and in-game resources like Tethras and Debristar." },
    ],
    cover: "/Minibase Photos/Dawnshard/Cover.jpeg",
    website: "https://playdawnshard.com/",
    discord: "https://discord.com/invite/kY4MXNmR3B",
    twitter: "https://x.com/play_dawnshard",
    tags: ["Strategy Game", "TCG", "P2E", "NFT Collectibles"],
    cta: "Start playing with your unique deck",
    ctaLink: "https://playdawnshard.com/"
  },
  {
    id: 2,
    name: "Anybody Problem",
    type: "CASUAL",
    desc: "A casual cozy supercollider game with onchain physics.",
    img: "/ap.png",
    overview: "ANYBODY PROBLEM is a casual, cozy supercollider game built with onchain physics. Built on Base, it uses zero-knowledge (ZK) cryptography to deliver a secure and engaging experience. In ANYBODY PROBLEM, you can mint your wins and climb the leaderboard to collect one-of-a-kind celestial bodies. Each day presents a new 'problem' (game), which you can collect as an NFT! These celestial bodies will appear in your wallet, and you can even play the game directly on OpenSea.",
    category: "Puzzle",
    images: ["/img5.png", "/img2.png","/img3.png","/img4.png"],
    faqData: [
      { question: "How to Play?", answer: "Kill Baddies, save Bodies. It's that simple. IFYKYK." },
      { question: "How do I mint the problem for each day?", answer: "You can mint the problem in the homepage." },
      { question: "Does the problem change everyday?", answer: "Yes. Each day has a new problem." },
    ],
    cover: "/gamecover.jpeg",
    website: "https://anybody.gg/",
    discord: "https://discord.com/invite/aEaEZT9Wr9",
    twitter: "https://x.com/triflelife",
    tags: ["Casual", "Puzzle", "Daily Challenge"],
    cta: "Solve today's problem",
    ctaLink: "https://anybody.gg/"
  },
  {
    id: 3,
    name: "EthXY",
    type: "RPG",
    desc: "An MMORPG where you build your hero and go on grand adventures.",
    img: "/ethxy.png",
    overview: "EthXY Summer Camp is a seasonal event hosted on the EthXY L3 Testnet rolled up to Base, offering players the chance to win a share of 1.5M SEXY tokens. Compete in minigames, earn $TEXY tokens, and boost your rewards by socketing Power Gems. Referrals allow players to earn more Testnet SEXY, with special badges and exclusive rewards for top performers.",
    category: "Role-Playing",
    images: ["/Minibase Photos/EthXY/F3F8PnZaIAA7zG_.jpeg", "/Minibase Photos/EthXY/GPz-ywdW8AAxC5c.jpeg", "/Minibase Photos/EthXY/GQUP4YEWkAEH3KV.jpeg","/Minibase Photos/EthXY/GRAyUAWasAEml9O.jpeg","/Minibase Photos/EthXY/GRA36TtbIAA8ZA6.png"],
    faqData: [
      { question: "How do I earn $TEXY?", answer: "You can earn $TEXY by playing minigames or staking $SEXY for daily yields." },
      { question: "What are Power Gems?", answer: "Power Gems boost your $TEXY yield based on the level of the gems you socket." },
      { question: "What rewards can I win?", answer: "Exclusive character skins, armors, and the top 1% will receive surprise loot." },
    ],
    cover: "/Minibase Photos/EthXY/Cover.jpeg",
    website: "https://ethxy.com/",
    discord: "https://discord.gg/ethxy",
    twitter: "https://twitter.com/ethxy",
    tags: ["Minigames", "P2E"],
    cta: "Join the Summer Camp fun",
    ctaLink: "https://ethxy.com/"
  },
  {
    id: 4,
    name: "Ultimate Champions",
    type: "E-SPORTS",
    desc: "Collect, manage, and trade your favourite football players.",
    img: "/uc.png",
    overview: "Ultimate Champions is a free-to-play fantasy Football and Basketball game powered by officially licensed digital cards as NFTs. Players act as team managers, building their dream squads to compete weekly for rewards. Each card represents a real-world athlete, and players can trade, buy, and sell their cards across the blockchain.",
    category: "Sports",
    images: ["/Minibase Photos/Ultimate Champions/F_RACNJbsAAcE9I.jpeg", "/Minibase Photos/Ultimate Champions/GaGYpJuXUAAkCwZ.png", "/Minibase Photos/Ultimate Champions/GKaAgoabsAAUe--.jpeg","/Minibase Photos/Ultimate Champions/GYfQ3GNWcAAORA5.jpeg","/Minibase Photos/Ultimate Champions/GYJxw7AXQAEf2me.png"],
    faqData: [
      { question: "How do I build a team?", answer: "Build your team by selecting cards representing real athletes in football and basketball." },
      { question: "What are digital cards?", answer: "Digital cards are NFTs representing real-world players that can be traded or collected." },
      { question: "How do I earn rewards?", answer: "Earn rewards by competing in weekly matches and rising through the ranks." },
    ],
    cover: "/Minibase Photos/Ultimate Champions/Cover.jpeg",
    website: "https://beta.ultimate-champions.com/",
    discord: "https://discord.com/invite/6V7drqvpyK",
    twitter: "https://x.com/UltiChamps",
    tags: ["E-Sports", "TCG"],
    cta: "Manage your dream team today",
    ctaLink: "https://beta.ultimate-champions.com/"
  },
  {
    id: 5,
    name: "Fren Pet",
    type: "CREATURE COLLECTING",
    desc: "Raise, train, and battle with your onchain fren!",
    img: "/fren.png",
    overview: "Fren Pet is an idle game built on the Base blockchain where players can own, upgrade, and grow their virtual pet. By minting a pet and upgrading it, players unlock more features, earn pGOLD, and share in the ecosystem's ETH rewards. Fren Pet allows for up to 10 free daily transactions and offers a Stake-to-Play (S2P) model for advanced gameplay.",
    category: "Simulation",
    images: [ "/Minibase Photos/Fren Pet/GHoL17sWgAAJVDX.png", "/Minibase Photos/Fren Pet/GSO9DxVWAAAPzJY.jpeg","/Minibase Photos/Fren Pet/GX37FADXwAAf9tT.png","/Minibase Photos/Fren Pet/GYLJd7EWoAIMn_s.jpeg","/Minibase Photos/Fren Pet/GZIVwGMWAAAJfan.jpeg"],
    faqData: [
      { question: "How do I mint a pet?", answer: "Mint your pet by joining Fren Pet via the desktop or mobile app." },
      { question: "What happens when I reach my daily transaction limit?", answer: "Your limit resets every 24 hours, so you can continue playing the next day." },
      { question: "What is Stake-to-Play (S2P)?", answer: "S2P allows you to stake assets in the game to unlock special features and rewards." },
    ],
    cover: "/Minibase Photos/Fren Pet/GHoL0yuXUAAmMnD.png",
    website: "https://frenpet.xyz/",
    discord: "https://discord.com/invite/u2R3VauhBg",
    twitter: "https://x.com/frenpetonbase",
    tags: ["P2E", "Casual Game", "Cozy Games"],
    cta: "Adopt your first Fren Pet now",
    ctaLink: "https://frenpet.xyz/"
  },
  {
    id: 6,
    name: "Fit Club",
    type: "P2E",
    desc: "Workout, compete, and earn on your onchain fitness journey.",
    img: "/fc.png",
    overview: "Fit Club is an onchain fitness game where players can own and customize their character to compete in fitness challenges and earn ETH rewards. Starting with an overweight character, players progress through workouts to improve their character's fitness and compete against others. Fit Club promotes a skill-based, story-driven gaming experience on the Base blockchain.",
    category: "Health & Fitness",
    images: ["/Minibase Photos/Fit Club/GV_suASWMAAT00v.jpeg", "/Minibase Photos/Fit Club/GWjdj_xWMAE1Rcs.jpeg", "/Minibase Photos/Fit Club/GWm949tWMAAMuMu.jpeg","/Minibase Photos/Fit Club/GZSmkWZXQAA_ng7.jpeg"],
    faqData: [
      { question: "How do I create a character?", answer: "Sign up and create your character, who starts off overweight but improves with gameplay." },
      { question: "What can I earn by playing?", answer: "Earn ETH rewards by competing in fitness challenges and progressing in the game." },
      { question: "Is Fit Club luck-based?", answer: "No, Fit Club focuses on skill-based gameplay where progress is earned through workouts." },
    ],
    cover: "/Minibase Photos/Fit Club/Cover.jpeg",
    website: "https://www.fitclub.tech/",
    discord: "https://x.com/fitclubonbase",
    twitter: "https://x.com/fitclubonbase",
    tags: ["Lifestyle Game", "P2E"],
    cta: "Start your fitness journey today",
    ctaLink: "https://www.fitclub.tech/"
  },
  {
    id: 7,
    name: "CityVerse Tycoon",
    type: "SIMULATION",
    desc: "Buy, sell, and manage properties in a virtual, onchain city.",
    img: "/cvt.png",
    overview: "Cityverse Tycoon combines the thrill of real estate board games with blockchain innovation. Players start as Renters and work their way up to becoming property Owners, transforming physical properties into digital NFTs. Engage in activities, earn rewards, and strategically upgrade properties to become a real-estate tycoon in this immersive game. With gameplay involving dice rolls, raids, and property visits, Cityverse Tycoon offers a competitive yet casual experience that merges the virtual and real world.",
    category: "Strategy",
    images: ["/Minibase Photos/Cityverse Tycoon/GOnFoH0a4AIZtkF.jpeg", "/Minibase Photos/Cityverse Tycoon/GXMn0GNakAABToy.jpeg", "/Minibase Photos/Cityverse Tycoon/GY-k7iibAAEibft.jpeg","/Minibase Photos/Cityverse Tycoon/GYVJYtZbcAAGf7X.jpeg"],
    faqData: [
      { question: "How do I start as a Renter?", answer: "Log in and participate in activities at other players' properties to gain experience and rewards." },
      { question: "Can I own buildings?", answer: "Yes, as you accumulate rewards, you can purchase your own buildings and unlock bigger rewards." },
      { question: "What strategies can I use?", answer: "Use strategic upgrades and Piggy multipliers to maximize your earnings and progress." },
    ],
    cover: "/Minibase Photos/Cityverse Tycoon/Cover.jpeg",
    website: "https://cityversetycoon.com/",
    discord: "https://discord.com/invite/cityversetycoon",
    twitter: "https://x.com/CityVerseTycoon",
    tags: ["Casual Game", "Strategy", "P2E", "Real Estate"],
    cta: "Start building your virtual empire now",
    ctaLink: "https://cityversetycoon.com/"
  },
  {
    id: 8,
    name: "Everdawn",
    type: "SIMULATION",
    desc: "Free-to-Play, 3D Tactical Trading Card Game.",
    img: "/ec.png",
    overview: "Everdawn Champions is a free-to-play 3D Tactical Trading Card Game (TCG) where your cards come to life in vivid gameplay. Developed by Nexus Interactive, the game combines strategic card combat with cutting-edge Web3 economies. Players can engage in tactical battles, using unique card mechanics to outsmart their opponents. The game is powered by $NXI tokens, providing deep liquidity and rewards across the Nexus ecosystem.",
    category: "Strategy",
    images: ["/Minibase Photos/Everdawn/Screenshot 2024-10-18 at 12.48.12 AM.png", "/Minibase Photos/Everdawn/Screenshot 2024-10-18 at 12.47.55 AM.png", "/Minibase Photos/Everdawn/GY6fq2IbAAE_1j3.jpeg"],
    faqData: [
      { question: "How do I earn rewards in Everdawn Champions?", answer: "Earn rewards by engaging in tactical battles and climbing the ranks using $NXI tokens." },
      { question: "What makes the cards unique?", answer: "Each card comes to life with 3D animations, offering a unique gameplay experience." },
      { question: "How do I get involved in the Nexus ecosystem?", answer: "You can participate in Nexus Play's games and trade using $NXI tokens across the platform." },
    ],
    cover: "/Minibase Photos/Everdawn/Screenshot 2024-10-18 at 12.48.36 AM.png",
    website: "https://www.nexusinteractive.io/games/everdawn-champions",
    discord: "https://discord.com/invite/D4qBJEHee7",
    twitter: "https://x.com/EverdawnChamp",
    tags: ["TCG", "Strategy Game", "P2E"],
    cta: "Join the battle and bring your cards to life",
    ctaLink: "https://www.nexusinteractive.io/games/everdawn-champions"
  },
  {
    id: 9,
    name: "Pixotchi",
    type: "FARMING",
    desc: "Grow, strategize, and earn rewards as you cultivate your garden on Base!",
    img: "/p.jpeg",
    overview: "Pixotchi brings the serene world of gardening to blockchain gaming. Set on the Base platform, players can grow and cultivate their digital gardens while earning rewards in $SEED tokens. Inspired by Fren Pet, Pixotchi offers a fun, casual mobile experience with smart contracts ensuring seamless gameplay. Build your garden, earn rewards, and strategize your way to becoming the ultimate gardener in this blockchain-based ecosystem.",
    category: "Simulation",
    images: ["/Minibase Photos/Pixotchi/GPLtI54XgAAXPmz.jpeg", "/Minibase Photos/Pixotchi/GPvKcM-XsAATgxf.png", "/Minibase Photos/Pixotchi/GSj3GRIWwAE7tAD.jpeg","/Minibase Photos/Pixotchi/GY-y0t8W0AAa-CN.jpeg"],
    faqData: [
      { question: "How do I start playing Pixotchi?", answer: "Install the Pixotchi PWA on your device, create a wallet using Privy, and start growing your garden." },
      { question: "What is $SEED?", answer: "$SEED is the in-game currency that players earn and use to upgrade their gardens." },
      { question: "Can I play on both iOS and Android?", answer: "Yes, Pixotchi is available as a PWA for both iOS and Android devices." },
    ],
    cover: "/Minibase Photos/Pixotchi/Cover.jpeg",
    website: "https://app.pixotchi.tech/",
    discord: "https://app.pixotchi.tech/",
    twitter: "https://x.com/pixotchi",
    tags: ["Casual Game", "P2E", "Cozy Games"],
    cta: "Start growing your digital garden",
    ctaLink: "https://app.pixotchi.tech/"
  },
  {
    id: 10,
    name: "Cat Town",
    type: "CASUAL",
    desc: "Cozy, onchain game inspired by Animal Crossing.",
    img: "/cat.jpeg",
    overview: "Cat Town is a cozy DeFi game on Base where players build their feline empire by purchasing cats and combining floofs to increase their ETH yield and earn $KIBBLE rewards. Inspired by Stardew Valley and Animal Crossing, this idle game lets players grow their cat population to generate floofs, which can be used to mint more cats or sold for ETH. Engage in minigames to earn additional rewards and accessories for your cats, while exploring a town full of interactive features.",
    category: "Health & Fitness",
    images: ["/Minibase Photos/Cat Town/GJ8GHVuXkAA-XG0.png", "/Minibase Photos/Cat Town/GK0OeewWoAAszB3.png", "/Minibase Photos/Cat Town/GMXdv-OXoAA5btD.jpeg","/Minibase Photos/Cat Town/GNTZt1dXcAEaNDh.png"],
    faqData: [
      { question: "How do I earn ETH in Cat Town?", answer: "You earn ETH passively by increasing your cat population and selling floofs." },
      { question: "What is $KIBBLE used for?", answer: "$KIBBLE is the in-game currency used to purchase accessories, cosmetics, and items to enhance your gameplay." },
      { question: "Can I sell my cats?", answer: "Not currently, but plans are in place to allow selling cats in the future, with a tax applied." },
    ],
    cover: "/Minibase Photos/Cat Town/Cover.jpeg",
    website: "https://cat.town/",
    discord: "https://discord.com/invite/cattown",
    twitter: "https://x.com/CatTownBase",
    tags: ["DeFi", "Play to Earn", "Casual Game"],
    cta: "Start building your feline empire, lmeow",
    ctaLink: "https://cat.town/"
  },
  {
    id: 11,
    name: "Atari X",
    type: "CLASSIC",
    desc: "Play Atari classics like Asteroids and Breakout onchain.",
    img: "/atari.jpeg",
    overview: "Atari X brings the nostalgia of classic Atari games into the Web3 era. The Atari Club offers a unique platform for gamers to vote on game development, play new releases early, and access exclusive discounts. With a focus on both community engagement and innovation, Atari X allows players to shape the future of retro gaming while enjoying modern Web3 rewards. Playtest the newest titles and earn rewards, all while connecting with other fans in the ultimate gaming club.",
    category: "CLASSIC",
    images: ["/Minibase Photos/Atari X/GTcIBuRWYAAZDGT.jpeg", "/Minibase Photos/Atari X/GTQbE4OXEAAuJ04.jpeg", "/Minibase Photos/Atari X/Screenshot 2024-10-18 at 12.33.47 AM.png"],
    faqData: [
      { question: "What is the Atari Club?", answer: "Atari Club is a community-driven platform where fans can vote on new games, play early releases, and access exclusive rewards." },
      { question: "How do I play new Atari games?", answer: "As a member of the Atari Club, you can playtest new games before their official release." },
      { question: "What rewards do I get for being part of the club?", answer: "Club members gain early access to releases, special discounts, and a say in Atari's future projects." },
    ],
    cover: "/Minibase Photos/Atari X/Cover.png",
    website: "https://www.atari.club/",
    discord: "http://discord.gg/atariclub",
    twitter: "https://x.com/AtariX",
    tags: ["Retro Games", "Community Hub"],
    cta: "Join the Atari Club today",
    ctaLink: "https://www.atari.club/"
  },
  {
    id: 12,
    name: "GangstaVerse",
    type: "P2E",
    desc: "Free-to-Play, 3D Tactical Trading Card Game.",
    img: "/gv.jpeg",
    overview: "GangstaVerse is a multi-chain virtual world where players can collect unique gangsters and detectives as NFTs, battle in GangWars, and own land in the Emerald City. Originating on the ICON blockchain, GangstaVerse now expands across multiple chains, including Base, where players can dive into a thrilling gangster-themed battle game. With weapons, items, and unique strategies, GangWars is the ultimate test of dominance in the digital underworld.",
    category: "P2E",
    images: ["/Minibase Photos/Gangstaverse/FtharwXXoAIyMRS.png", "/Minibase Photos/Gangstaverse/FthljvCaYAAhdvg.jpeg", "/Minibase Photos/Gangstaverse/FwzI7sXWIAI5sqQ.jpeg","/Minibase Photos/Gangstaverse/GAB0nN1X0AAcMiU.jpeg"],
    faqData: [
      { question: "What is GangstaVerse?", answer: "GangstaVerse is a multi-chain virtual world featuring gangster and detective NFTs, a battle game, and land ownership in the Emerald City." },
      { question: "What is GangWars?", answer: "GangWars is a strategic battle game where players use their GangstaBet NFTs to fight for dominance and earn rewards." },
      { question: "Can I own land in GangstaVerse?", answer: "Yes, players can own land in the Emerald City and participate in the GangstaVerse ecosystem." },
    ],
    cover: "/Minibase Photos/Gangstaverse/Cover.jpeg",
    website: "https://linktr.ee/gangstaverse",
    discord: "http://discord.gg/atariclub",
    twitter: "https://x.com/GangstaVerse",
    tags: ["P2E", "Multi-chain Game", "NFT Collectibles"],
    cta: "Join the GangstaVerse and rule the streets",
    ctaLink: "https://linktr.ee/gangstaverse"
  }
]